version : '3'

services:
  api-service:
    build: ./api
    ports:
      - 5001:8000

  db:
      image: mysql:5.7
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=user
        - MYSQL_DATABASE=isl_db
      ports:
        - 3306:3306
      volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:      
